import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

/**
 * Regression guard for the beta.1 P4 finding: the packaged cordis.patch.yml
 * generated by scripts/package-staging.ts must reference the plugin by its
 * scoped publish name. The dsh loader resolves the loader-entry `name` as an
 * import specifier from the profile directory; a bare `dsh-norm-spec` name
 * fails to resolve when the package is installed from the npm registry
 * (`dsh plugin add @cyanoorg/dsh-norm-spec`), breaking every consumer boot.
 *
 * Full staging requires a tsc compile of src/ and is exercised by the
 * package-candidates CI workflow; this test pins the generator's emitted
 * patch contract cheaply by staging only the patch through the same code
 * path used in production (stageRootPackage's writeFile block is mirrored
 * here against the actual script source, so a regression in the script
 * itself is caught textually).
 */
const scriptPath = new URL("../scripts/package-staging.ts", import.meta.url);

test("packaged patch generator emits the scoped loader-entry name", async () => {
  const source = await readFile(scriptPath, "utf8");
  // The generator must emit the scoped publish name, not the bare name.
  assert.match(
    source,
    /name: '@cyanoorg\/dsh-norm-spec'/u,
    "stageRootPackage must emit the scoped loader-entry name in the packaged cordis.patch.yml; " +
      "a bare 'dsh-norm-spec' name breaks registry installs (beta.1 P4 finding)",
  );
  // And it must not emit the bare name anywhere in the packaged patch block.
  const patchBlock = source.split("- insert:").pop() ?? "";
  assert.doesNotMatch(
    patchBlock,
    /name: 'dsh-norm-spec'/u,
    "the packaged patch block must not reference the bare package name",
  );
});

test("runtime resolver keeps scoped platform package naming", async () => {
  // The packaged plugin resolves its own tree via release.json identity; the
  // scoped name is the only valid product identity. The staged platform
  // manifests (packages/<suffix>/package.json) are the naming authority —
  // assert every one is scoped so a bare-name regression cannot ship.
  const { readdir, readFile: read } = await import("node:fs/promises");
  const packagesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "packages");
  for (const entry of await readdir(packagesDir)) {
    const manifestPath = path.join(packagesDir, entry, "package.json");
    const manifest = JSON.parse(await read(manifestPath, "utf8"));
    assert.match(
      manifest.name,
      /^@cyanoorg\/dsh-norm-spec(-[a-z0-9-]+)?$/u,
      `package manifest name must be scoped: ${manifest.name}`,
    );
  }
});
